### PR TITLE
Improved performance, other fixes

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
Improved performance by removing redundant regular expressions, simplifying existing ones, and removing them when not needed.  Removed tracking parameters from URLs.  Other fixes minor enough to be included in this PR.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
Sorry, no, youre removing actually needed stuff. Its there for a reason.

**Comment by Gitoffthelawn** [comment]
No problem.  What reason?  I'm running the code without issues, but perhaps I'm not encountering an issue you've encountered.

**Comment by the-j0k3r** [comment]
1. Youre changing the theme name, definitely not.
2. Youre adding version bumps, big no, this is for internal use only.
3, Youre removing regex negating access to area51
4. Youre removing regex that encompass specific sites like `regexp("^https?://((chat|meta|es|ja|pt|ru)\\.)*stackoverflow\\.com.*")` and replacing it with stackexchange only.

image links youre removing bits like `?v=8f7dca5b94db` These point to specifc image versions.

All and all most of the regex for domain changes are wrong.

If you dont want to use our theme for stackoverflow because they have a native dark theme, thats OK, you dont have to use this.

**Comment by Gitoffthelawn** [comment]
No problem at all. Thanks for permission to fork.

**Comment by the-j0k3r** [comment]
Just follow the license requirements and all will be OK.

Also modified the PR title to match the intention.

**Comment by Gitoffthelawn** [comment]
@the-j0k3r Thanks for the tips.  BTW, the style here calls external resources (images).  It's not doing anything inappropriate, but it would be great if somehow it was disclosed.  I'm not sure exactly how it could be done, but it would be great if styles somehow had a disclaimer/indicator to indicate that they pull external resources.  Maybe even a tiny permission system to say "are you okay installing a style that uses external resources?".

Anyways, it's just a thought, and while we are chatting I thought I would mention it real quick.  I'm interested in hearing your thoughts on the topic.

Thanks again for the tips and ideas.

**Comment by the-j0k3r** [comment]
We can add something in readme, anything else not possible.

Also as for the external images they can be base64 encoded and that used instead, but tbh its low priority. Any such replacements have to be done properly and made sure its not breaking something where image is shown.

This takes time, time I dont have to ensure its correctly done.

**Comment by Gitoffthelawn** [comment]
@the-j0k3r Thank you for the feedback.  Take care.

**Comment by the-j0k3r** [comment]
I had a look, there only 1 external image, the rest are from StackOverflow/Stackexchange themselves

**Pull request closed without merging**
