### PR TITLE
Scrollbar for Firefox

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @vitaly-zdanevich!

We've actually created a [global style for scroll bars](https://github.com/StylishThemes/Overlay-Scrollbars) (repo has both global & GitHub styles) instead of incorporating them into every style.

**Comment by AfroThundr3007730** [comment]
Can't believe I just discovered overlay scrollbars today. Nice :)

**Comment by the-j0k3r** [comment]
Thanks @vitaly-zdanevich for PR, Since we have the scrollbars style @mottie mentioned, makes this superfluous.

**Comment by vitaly-zdanevich** [comment]
Ok but now on Stackoverflow I see scrollbar with white background.

**Comment by vitaly-zdanevich** [comment]
Oh I found that I just need to install this another global style :)

**Pull request closed without merging**
