### PR TITLE
Removed hero container and fixed button

### PR DESCRIPTION
**Pull request by Zeeex**
Removed hero container because it's too large and unneeded. You can manage account with the dedicated buttons in the top corner.

Fixed "Ask Question" button :hover event that was displaying white background.

### CODE REVIEW

**Comment by tambry** [comment]
Where's the hero container?

For me the "Ask Question" button doesn't display a white background when hovering it [on the main page](https://stackoverflow.com).

**Comment by Zeeex** [comment]
Hero Container is on the main page when not signed in.
"Ask question" button hover display is broken when inside a question.

**Comment by tambry** [comment]
This does indeed fix the "Ask question" button inside a question.  
I'm unable to confirm the hero container fix, as it's disappeared in favor of the SO developer survey link.

I'm just gonna assume it's correct.

**Comment by Zeeex** [comment]
The hero container is still there.
image

Yes this fix hides the container completely.

**Comment by tambry** [comment]
Ah, I was using [Undistractify StackOverflow](https://userstyles.org/styles/146704/undistractify-stackoverflow-enhanced), which apparently hid it.

As far as I'm concerned, the goal of this style is to simply make SO dark and not remove or modify the functionality itself. That said, @Mottie should probably chime in on this one.

**Comment by Mottie** [comment]
Sorry! I keep forgetting to follow up on this issue.

I agree that this style simply makes SE sites dark, but we do have some opinionated styles like hiding the job section and severely dimming the ads. I don't have a problem hiding the hero container, but can we be sure it will always only contain the duplicate log in form?

**Comment by Zeeex** [comment]
It seems very likely that it will always be that. Hero containers usually contain some sort of advertisement.

In this case, it's completely unneeded.

**Pull request merged**
