### PR TITLE
Fix mdhelp dropdowns

### PR DESCRIPTION
**Pull request by ImportTaste**
Before:
image

After:
image

### CODE REVIEW

**Comment by ImportTaste** [comment]
I tried doing this with `#mdhelp-links` at first, but when zooming in the page, it can create gaps along the border:
image

**Comment by the-j0k3r** [comment]
The actual solution is simpler than that now. Gimme a moment.

**Comment by the-j0k3r** [comment]
thx for PR, however https://github.com/StylishThemes/StackOverflow-Dark/commit/a8d6194a2a01b0010580db4ba7cca3c144ab72ef seems to be the way forward.

**Comment by ImportTaste** [comment]
Looks good, thanks.

**Pull request closed without merging**
