### PR TITLE
Fix correct answer checkmark & stared question icon's colors

### PR DESCRIPTION
**Pull request by Idomo**
Those icons should be noticeable, not gray like all other icons.

### CODE REVIEW

**Comment by skeets23** [comment]
This isn't enough, I think the rule needs to be removed (although, I don't know why it was added, so I could be wrong.)

It was added [19 hours ago](https://github.com/StylishThemes/StackOverflow-Dark/commit/fffef92406bf3ec96afbce5c2d77e27ccd89de9f#diff-461826e838232dd067ac76c1f6ee5ee7R1370).

It's also causing posts you've upvoted to look the same as posts you haven't. Check the attached screenshot, you can tell from the title that I've upvoted the answer, but the up and down vote icons are still the same color.

08_08-34-326x123-1dae9bb9e1

**Comment by Idomo** [comment]
@skeets23 Hmm you right, but I can see why this rule has been added, if you'll remove it via the inspection toll you'll see that there are some icons that with too dark background so you can't see them clearly, also their colors are different and it looks weird.

I think there are more icons with wrong colors then correct colors (like the ones I fixed), so it would be better using the `:not()` for the specific icons that have the correct colors.

I've updated the code so now the up/down votes should be highlighted when you click them.

**Comment by the-j0k3r** [comment]
This rule was added to avoid having to style dozens of icons manually (something I had started to do already a while back and removed in https://github.com/StylishThemes/StackOverflow-Dark/commit/fffef92406bf3ec96afbce5c2d77e27ccd89de9f#diff-461826e838232dd067ac76c1f6ee5ee7L1332), But, if each time theres an issue now the exclusion list will juts get longer and longer.

I think its probably better to revert to styling them individually though.

So Ill need to style all these manually instead. hold fire on this PR while I go back to 

Please post a link to the page with this issue, so when I revert back I ensure that I dont break these either.

FYI the pages with most of these icons is the jobs pages https://stackoverflow.com/jobs/279652/security-architect-tessian?so=i&pg=1&offset=-1 each job page has more and more of these.

**Comment by the-j0k3r** [comment]
Ive tried to address this in https://github.com/StylishThemes/StackOverflow-Dark/commit/75bc845694ad333da231005b3cb37876e2da7181, it seems to be working, though if you guys notice any more issues please let me know.

Click [here](https://github.com/StylishThemes/StackOverflow-Dark/raw/master/stackoverflow-dark.user.css) to update your style to 3.3.12 or check for updates via Stylus.

@Idomo thanks for your contribution, though going forward, its better for me not to fall into the same trap I fell by adding this rule ;)

**Comment by the-j0k3r** [comment]
Just as a warning and in case anyone notices any borders broken anywhere.

Ive removed the glob border-color in https://github.com/StylishThemes/StackOverflow-Dark/commit/2ec9fcc5e7095a131ab01fa9eaa98492a08b34a8

Ive been slowly fixing all borders I come across for a week or so, its time to drop it and deal with the aftermath like https://github.com/StylishThemes/StackOverflow-Dark/commit/6eff6d892793bdff196b82b676c67499400de349 for one.

If you guys notice anything around let me know. Thanks.

**Pull request closed without merging**
